/// prelude most of the symbols from gfx_hal and gfx_backend_*
pub use gfx_hal::{
    Backend as TB,
    adapter::{MemoryTypeId, Adapter, AdapterInfo},
    buffer,
    format::{Aspects, ChannelType, Format, Swizzle},
    image::{
        self as img, Access, Extent, Filter, Layout, Offset, SubresourceLayers, SubresourceRange,
        ViewCapabilities, ViewKind, WrapMode,
    },
    memory::{Barrier, Dependencies, Properties},
    pass::{
        Attachment, AttachmentLoadOp, AttachmentOps, AttachmentStoreOp, Subpass, SubpassDependency,
        SubpassDesc, SubpassRef,
    },
    pool::CommandPoolCreateFlags,
    pso::{
        AttributeDesc, BlendState, ColorBlendDesc, ColorMask, Comparison, DepthStencilDesc,
        DepthTest, Descriptor, DescriptorRangeDesc, DescriptorSetLayoutBinding, DescriptorSetWrite,
        DescriptorType, Element, EntryPoint, GraphicsPipelineDesc, GraphicsShaderSet,
        PipelineStage, Rasterizer, Rect, ShaderStageFlags, StencilTest, VertexBufferDesc, Viewport,
    },
    command::{
        CommandBuffer,
        BufferImageCopy,
        ClearColor,
        ClearDepthStencil,
        ClearValue,
        OneShot,
        Primary,
    },
    queue::Submission,
    window::Extent2D,
    Backbuffer,
    DescriptorPool,
    Device,
    FrameSync,
    Graphics,
    Instance,
    MemoryType,
    PhysicalDevice,
    Primitive,
    Surface,
    SwapImageIndex,
    Swapchain,
    SwapchainConfig,
    SurfaceCapabilities,
};
pub use backend::Backend as B;